# Generated by Django 5.0.1 on 2024-01-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_student_age'),
        ('mobile', '0002_remove_student_password'),
    ]

    operations = [
    ]
