# Generated by Django 5.0.1 on 2024-01-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_merge_20240113_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
